### ISSUE TITLE
Fix Binomial Sampling 

### ISSUE THREAD

**Issue by DE0CH** [ndangtt/1LLGA#3]
There are still a few places with binomial sampling that PR #2 does not address. 

- In `source-code.algorithms.utils.crossover`, `l = np.random.binomial(n,c)`, which means `l` can equal to `0`. Not sure if this is intentional.

- In `source-code.algorithms.utils.crossover_different_bits`
```python
    l = np.random.binomial(nD,c)
    while l == 0 or l == nD:
        l = np.random.binomial(nD,c)
```

I am not sure how probable it is for `l == nD` so I didn't fix this function yet.

**Comment by ndangtt** [comment]
Thanks for pointing this out. I think we probably don't use this function anymore (it was there during the experimental phase where we tried multiple implementation options before fixing on one). So it's probably okay to leave it.

If you agree with this please feel free to close the issue :)

**Comment by DE0CH** [comment]
I see thanks!
